aws_region    = "us-east-1"
instance_name = "cloud-guardian-instance"
project       = "Cloud Guardian"
instance_type = "t2.micro"
ami_id        = "ami id"
key_name      = "key pair"
ssh_cidr      = "0.0.0.0/0" 
